# Generated by Django 6.0.3 on 2026-03-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_booking_at_book_ticket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booking_at',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
