# Generated by Django 6.0.3 on 2026-03-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_booking_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booking_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
