# Generated by Django 6.0.3 on 2026-03-27 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_timings', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.movie')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.screen')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('screen', 'show_timings'), name='unique_show')],
            },
        ),
    ]
