# Generated by Django 6.0.3 on 2026-03-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_screen_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='locality',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
