# Generated by Django 6.0.3 on 2026-03-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_venue_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='shows.genre'),
        ),
    ]
