# Generated by Django 6.0.3 on 2026-03-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_remove_movie_genres_alter_show_movie_delete_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='capacity',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AddField(
            model_name='show',
            name='ticket_price',
            field=models.PositiveIntegerField(default=250),
        ),
    ]
