# Generated by Django 6.0.3 on 2026-03-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, max_length=500)),
                ('certification', models.CharField(max_length=10)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.URLField(default='https://betravingknows.com/wp-content/uploads/2017/06/video-movie-placeholder-image-grey.png')),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
