# Generated by Django 6.0.3 on 2026-03-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.PositiveIntegerField(default=120, help_text='Runtime in minutes'),
        ),
    ]
