# Generated by Django 6.0.3 on 2026-03-30 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_account_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.city'),
        ),
    ]
